fail_fast: true
default_stages: [pre-commit, pre-push]
minimum_pre_commit_version: 3.5.0


repos:
  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11
        stages: [pre-commit]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        stages: [pre-commit]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [pre-commit]